language: cpp

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
 - gcc

sudo: required
dist: trusty

notifications:
  email:
    - spam@kdmurray.id.au

before_install:
  - sudo apt-get install -yy
        libyaml-cpp-dev
        libboost-dev
        libbz2-dev
        zlib1g-dev
        python-pip
  - pip install --user -r docs/requirements.txt

install:
 - mkdir build
 - mkdir target

script:
 - cd build
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - ctest --verbose
 - make install
 - cd ../docs
 - make html
 - cd ..
 - test -f target/bin/trimit
 - rm -rf target
 -  if [ -n "$TRAVIS_TAG" ] && [ "${BUILD_TYPE}" == "Release" ] ;
    then
        make -f src/Makefile.static ;
    fi ;
