language: cpp

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
 - gcc

sudo: required
dist: trusty

notifications:
  email:
    - spam@kdmurray.id.au

before_install:
  - sudo apt-get install -yy
        libyaml-cpp-dev
        libboost-dev
        libbz2-dev
        zlib1g-dev
        python-sphinx

install:
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - ctest --verbose
 - make install
 - test -f ../target/bin/trimit
 -  if [ -n "$TRAVIS_TAG" ];
    then;
        make -f src/Makefile.static;
    fi;
